title: Light Painter
email: semagnum+lightpainter@gmail.com
description: Official documentation
github_username: semagnum

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme